### ISSUE TITLE
how can i train it with my own data?

### ISSUE THREAD

**Issue by Marcus208** [zhreshold/mxnet-ssd#143]
i have some pictures used to train faster-rcnn. it has the only type named 'ship'. but when i use'bash tools/prepare_pascal.sh', error comes to me:
saving list to disk...
Traceback (most recent call last):..
  File "/home/marcus/mxnet-ssd/tools/prepare_dataset.py", line 98, in <module>
    db.save_imglist(args.target, root=args.root_path)
  File "/home/marcus/mxnet-ssd/dataset/imdb.py", line 93, in save_imglist
    raise RuntimeError("No image in imdb")
RuntimeError: No image in imdb
saving list to disk...
Traceback (most recent call last):..
  File "/home/marcus/mxnet-ssd/tools/prepare_dataset.py", line 98, in <module>
    db.save_imglist(args.target, root=args.root_path)
  File "/home/marcus/mxnet-ssd/dataset/imdb.py", line 93, in save_imglist
    raise RuntimeError("No image in imdb")
RuntimeError: No image in imdb

what should i do?

**Comment by zhreshold** [comment]
make sure you have correct path pointing to the image data folder

**Comment by alexschultz** [comment]
I'm hitting the same issue. I have my training data in "data/VOCdevkit/VOC2018/..."

saving list to disk...
Traceback (most recent call last):..
  File "tools/prepare_dataset.py", line 118, in <module>
    db.save_imglist(args.target, root=args.root_path)
  File "/home/aschu/development/apache-incubator/mxnet/incubator-mxnet/example/ssd/tools/../dataset/imdb.py", line 110, in save_imglist
    raise RuntimeError("No image in imdb")
RuntimeError: No image in imdb

**Comment by tony2278** [comment]
me too......
