### ISSUE TITLE
Training on new dataset

### ISSUE THREAD

**Issue by Rizhiy** [zhreshold/mxnet-ssd#154]
I'm trying to train on Coco 2017, and I get the following error:
```
Traceback (most recent call last):
  File "train.py", line 134, in <module>
    voc07_metric=args.use_voc07_metric)
  File "/home/rizhiy/pedestrian-detection/mxnet-ssd/train/train_net.py", line 267, in train_net
    monitor=monitor)
  File "/home/rizhiy/miniconda3/envs/mxnet-ssd/lib/python3.6/site-packages/mxnet/module/base_module.py", line 496, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "/home/rizhiy/miniconda3/envs/mxnet-ssd/lib/python3.6/site-packages/mxnet/module/module.py", line 735, in update_metric
    self._exec_group.update_metric(eval_metric, labels)
  File "/home/rizhiy/miniconda3/envs/mxnet-ssd/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 582, in update_metric
    eval_metric.update_dict(labels_, preds)
  File "/home/rizhiy/miniconda3/envs/mxnet-ssd/lib/python3.6/site-packages/mxnet/metric.py", line 108, in update_dict
    self.update(label, pred)
  File "/home/rizhiy/pedestrian-detection/mxnet-ssd/train/metric.py", line 39, in update
    prob = prob[mask, indices]
IndexError: index 89 is out of bounds for axis 1 with size 81
```
As I understand it tries to suggest class 89 when there are only 81 classes. What might be the problem?

I used the following command to start the training:
```
python train.py --label-width 560 --num-class 80 --class-names dataset/names/mscoco.names 
```

**Comment by zhreshold** [comment]
Did you mesh up with other challenges which might have more than 80 classes?

**Comment by Rizhiy** [comment]
No, I used mscoco 2017 instead of 2014, but I believe it still has 80 classes.

**Comment by Rizhiy** [comment]
I have also tried training on coco 2014 and still get the same error.

**Comment by Rizhiy** [comment]
It appears that while coco has 80 `object` classes, it has 90 `stuff` classes. So we either need to set `num-class` to 90 or  user [this](https://github.com/aghagol/caffe-ssd/blob/master/data/coco/labels.txt) for conversion.
