### ISSUE TITLE
check failed error when trainning on model Inception-v3 512x512

### ISSUE THREAD

**Issue by yanhn** [zhreshold/mxnet-ssd#157]
I followed the tutorial and succeed tranning a detector with my own dataset using VGG16_reduced 300x300. And I got the right result using  `demo.py` `deploy.py` `evaluate.py` so I think my data format and evrioment are correct. But when I extend the experiments to use model Inception-v3 512x512，"Check failed" error occurred.
The spot looks like this:

[11:27:41] C:\workspace\opensource\incubator-mxnet\src\io\iter_image_det_recordio.cc:281: ImageDetRecordIOParser: C:\workspace\opensource\mxnet-ssd\data\train.rec, use 7 threads for decoding.. 
[11:27:43] C:\workspace\opensource\incubator-mxnet\src\io\iter_image_det_recordio.cc:334: ImageDetRecordIOParser: C:\workspace\opensource\mxnet-ssd\data\train.rec, label padding width: 350
[11:27:45] C:\workspace\opensource\incubator-mxnet\src\io\iter_image_det_recordio.cc:281: ImageDetRecordIOParser: C:\workspace\opensource\mxnet-ssd\data\val.rec, use 7 threads for decoding..
[11:27:46] C:\workspace\opensource\incubator-mxnet\src\io\iter_image_det_recordio.cc:334: ImageDetRecordIOParser: C:\workspace\opensource\mxnet-ssd\data\val.rec, label padding width: 350
INFO:root:Start training with (gpu(0)) from pretrained model C:/workspace/opensource/mxnet-ssd/model/ssd_inceptionv3_512
[11:27:47] C:\workspace\opensource\incubator-mxnet\src\nnvm\legacy_json_util.cc:190: Loading symbol saved by previous version v0.12.0. Attempting to upgrade...
[11:27:47] C:\workspace\opensource\incubator-mxnet\src\nnvm\legacy_json_util.cc:198: Symbol successfully upgraded!
Using mxnet as:
<module 'mxnet' from 'C:\Users\owl\Anaconda3\envs\dl27\lib\site-packages\mxnet-1.0.0-py2.7.egg\mxnet\__init__.pyc'>
Warning: using pre-installed version of mxnet may cause unexpected error...
(export MXNET_EXAMPLE_SSD_DISABLE_PRE_INSTALLED=1) to prevent loading pre-installed mxnet.
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    tensorboard=args.tensorboard)
  File "C:\workspace\opensource\mxnet-ssd\train\train_net.py", line 354, in train_net
    monitor=monitor)
  File "C:\Users\owl\Anaconda3\envs\dl27\lib\site-packages\mxnet-1.0.0-py2.7.egg\mxnet\module\base_module.py", line 464, in fit
    allow_missing=allow_missing, force_init=force_init)
  File "C:\Users\owl\Anaconda3\envs\dl27\lib\site-packages\mxnet-1.0.0-py2.7.egg\mxnet\module\module.py", line 308, in init_params
    _impl(desc, arr, arg_params)
  File "C:\Users\owl\Anaconda3\envs\dl27\lib\site-packages\mxnet-1.0.0-py2.7.egg\mxnet\module\module.py", line 296, in _impl
    cache_arr.copyto(arr)
  File "C:\Users\owl\Anaconda3\envs\dl27\lib\site-packages\mxnet-1.0.0-py2.7.egg\mxnet\ndarray\ndarray.py", line 1876, in copyto
    return _internal._copyto(self, out=other)
  File "<string>", line 25, in _copyto
  File "C:\Users\owl\Anaconda3\envs\dl27\lib\site-packages\mxnet-1.0.0-py2.7.egg\mxnet\_ctypes\ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "C:\Users\owl\Anaconda3\envs\dl27\lib\site-packages\mxnet-1.0.0-py2.7.egg\mxnet\base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [11:27:54] c:\workspace\opensource\incubator-mxnet\src\operator\tensor\../elemwise_op_common.h:123: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node  at 0-th output: expected [84], got [8]

The parameters I use is shown below:
`--gpus 0 --batch-size 16 --lr 0.001 --class-names head --num-class 1 --epoch 1 --network vgg16_reduced --pretrained C:/workspace/opensource/mxnet-ssd/model/vgg16_reduced --data-shape 512`
This works fine. But when I change the `network` and `pretrainedpath` to
`--gpus 0 --batch-size 16 --lr 0.001 --class-names head --num-class 1 --epoch 215 --data-shape 512 --network inceptionv3 --pretrained C:/workspace/opensource/mxnet-ssd/model/ssd_inceptionv3_512`
Then I got the error above.

According to the error log, it is most likey that my `num_class` is not set correct. It used the origin model  of 20 detection classes instead of my own 1 class.
I checked the args after `args = parse_args()`, no problems.
I searched `0-th output` in `ssd_inceptionv3_512-symbol.json` but nothing matched. And I searched output num 84 still found nothing. 
My main doubt is either my parameters or the json config. I am new to mxnet and ssd, not that familiar with mx.symbol api, trying to print the args out. Anything would be helpful, thanks.

**Comment by zhreshold** [comment]
If you have different number of classes, we call it fine-tune task. You can checkout --finetune argument. 
The reason is convolutional channel will need to be replaced to fit the new class numbers.

**Comment by yanhn** [comment]
Thanks a lot! It works for me for now. 
First I change the model name from `mxnet-ssd/model/ssd_inceptionv3_512-0215.params` to `mxnet-ssd/output/exp1/ssd-0001.params`, so as the `.json` file.
Then I used the parameters as below and no error occured
`--gpus 0 --network inceptionv3 --data-shape 512 --class-names head --num-class 1 --batch-size 32 --finetune 1`
I'd check the trained model and tell if this way trained model ok. Thanks again.

**Comment by yanhn** [comment]
@zhreshold thanks,  it solved my question well.
