### ISSUE TITLE
 'module' object has no attribute 'float16'

### ISSUE THREAD

**Issue by PPeiMi** [zhreshold/mxnet-ssd#16]
Hi, after install the mxnet package, I tried to run the `train_mnist.py,` but there are some problems:

```
sudo python example/image-classification/train_mnist.py --network lenet --gpus 0
Traceback (most recent call last):
  File "example/image-classification/train_mnist.py", line 1, in <module>
    import find_mxnet
  File "/home/PPeiMi/mxnet-ssd2/mxnet/example/image-classification/find_mxnet.py", line 2, in <module>
    import mxnet as mx
  File "/home/PPeiMi/mxnet-ssd2/mxnet/python/mxnet/__init__.py", line 9, in <module>
    from . import ndarray
  File "/home/PPeiMi/mxnet-ssd2/mxnet/python/mxnet/ndarray.py", line 25, in <module>
    np.float16 : 2,
AttributeError: 'module' object has no attribute 'float16'
```
My python version is 2.6.

**Comment by zhreshold** [comment]
Be sure to follow the installation guide, BTW, use official repo for the mnist example
