### ISSUE TITLE
RuntimeError: multi_feat_2_conv_1x1_conv_bias is not presented when I use the VGG16 which downloaded from the homepage

### ISSUE THREAD

**Issue by ChangliangSun** [zhreshold/mxnet-ssd#162]
Hello. I try to use the VGG16 to run demo. but I failed with errors. When I use the resnet50 to run demo, it successed. Error details about using VGG16 show below.

> root@15d198e46951:/source-code/mxnet-ssd# python demo.py --gpu 0 --network vgg16_reduced --data-shape 512
Using mxnet as:
<module 'mxnet' from '/usr/local/lib/python2.7/dist-packages/mxnet/__init__.pyc'>
Warning: using pre-installed version of mxnet may cause unexpected error...
(export MXNET_EXAMPLE_SSD_DISABLE_PRE_INSTALLED=1) to prevent loading pre-installed mxnet.
[09:52:33] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.9.5. Attempting to upgrade...
[09:52:33] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
[09:52:36] src/operator/././cudnn_algoreg-inl.h:112: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[09:52:38] src/operator/convolution.cu:119: This convolution is not supported by cudnn, MXNET convolution is applied.
Traceback (most recent call last):
  File "demo.py", line 121, in <module>
    ctx, len(class_names), args.nms_thresh, args.force_nms)
  File "demo.py", line 38, in get_detector
    detector = Detector(net, prefix, epoch, data_shape, mean_pixels, ctx=ctx)
  File "/source-code/mxnet-ssd/detect/detector.py", line 40, in __init__
    self.mod.set_params(args, auxs)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/module.py", line 337, in set_params
    allow_extra=allow_extra)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/module.py", line 296, in init_params
    _impl(desc, arr, arg_params)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/module.py", line 287, in _impl
    raise RuntimeError("%s is not presented" % name)
RuntimeError: multi_feat_2_conv_1x1_conv_bias is not presented

> root@15d198e46951:/source-code/mxnet-ssd# python demo.py --gpu 0 --network resnet50 --data-shape 512
Using mxnet as:
<module 'mxnet' from '/usr/local/lib/python2.7/dist-packages/mxnet/__init__.pyc'>
Warning: using pre-installed version of mxnet may cause unexpected error...
(export MXNET_EXAMPLE_SSD_DISABLE_PRE_INSTALLED=1) to prevent loading pre-installed mxnet.
[09:53:23] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.10.1. Attempting to upgrade...
[09:53:23] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
[09:53:25] src/operator/././cudnn_algoreg-inl.h:112: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Detection time for 1 images: 0.1128 sec
hello

So thanks for your help.

**Comment by zhreshold** [comment]
use `--network xxx` for different networks

**Comment by ChangliangSun** [comment]
@zhreshold  I used `python demo.py --gpu 0 --network vgg16_reduced --data-shape 512` when run VGG16net and python demo.py --gpu 0 --network resnet50 --data-shape 512 for resnet

**Comment by ChangliangSun** [comment]
I trained a model that pretrained by vgg16_reduced_300, and then use that model what I trained to run demo, it succeeded.
`python demo.py --gpu 0 --network vgg16_reduced --epoch 400 --prefix ./model/ssd --data-shape 300 --image ./data/demo/street.jpg`

**Comment by AaronYoooooooog** [comment]
i meet the same problem that  "multi_feat_2_conv_1x1_conv_bias is not presented", when i use vgg16_reduced network for evaluation, and I try  vgg16_reduced_300 pretrained mode, which also display this error, how to solve this problem?
