### ISSUE TITLE
Error while executing bash tools/prepare_pascal.sh command

### ISSUE THREAD

**Issue by guruvishnuvardan** [zhreshold/mxnet-ssd#187]
Please note, I am getting the following error while executing bash tools/prepare_pascal.sh command, Can you pls let me know the cause of the error

amcsgpu@amcsgpu:~/Zero/mxnet-ssd-master$ bash tools/prepare_pascal.sh
filtering images with no gt-labels. can abort filtering using *true_negative* flag
... remaining 5011/5011 images.  
filtering images with no gt-labels. can abort filtering using *true_negative* flag
... remaining 11540/11540 images.  
saving list to disk...
List file /home/amcsgpu/Zero/mxnet-ssd-master/tools/../data/train.lst generated...
usage: im2rec.py [-h] [--list] [--exts EXTS [EXTS ...]] [--chunks CHUNKS]
                 [--train-ratio TRAIN_RATIO] [--test-ratio TEST_RATIO]
                 [--recursive] [--no-shuffle] [--pass-through]
                 [--resize RESIZE] [--center-crop] [--quality QUALITY]
                 [--num-thread NUM_THREAD] [--color {-1,0,1}]
                 [--encoding {.jpg,.png}] [--pack-label]
                 prefix root
im2rec.py: error: unrecognized arguments: --shuffle 1 1
Traceback (most recent call last):
  File "/home/amcsgpu/Zero/mxnet-ssd-master/tools/prepare_dataset.py", line 121, in <module>
    "--shuffle", str(int(args.shuffle)), "--pack-label", "1"])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/usr/local/lib/python2.7/dist-packages/mxnet/tools/im2rec.py', '/home/amcsgpu/Zero/mxnet-ssd-master/data/train.lst', '/home/amcsgpu/Zero/mxnet-ssd-master/data/VOCdevkit', '--shuffle', '1', '--pack-label', '1']' returned non-zero exit status 2
filtering images with no gt-labels. can abort filtering using *true_negative* flag
... remaining 4952/4952 images.  
saving list to disk...
List file /home/amcsgpu/Zero/mxnet-ssd-master/tools/../data/val.lst generated...
usage: im2rec.py [-h] [--list] [--exts EXTS [EXTS ...]] [--chunks CHUNKS]
                 [--train-ratio TRAIN_RATIO] [--test-ratio TEST_RATIO]
                 [--recursive] [--no-shuffle] [--pass-through]
                 [--resize RESIZE] [--center-crop] [--quality QUALITY]
                 [--num-thread NUM_THREAD] [--color {-1,0,1}]
                 [--encoding {.jpg,.png}] [--pack-label]
                 prefix root
im2rec.py: error: unrecognized arguments: --shuffle 1 1
Traceback (most recent call last):
  File "/home/amcsgpu/Zero/mxnet-ssd-master/tools/prepare_dataset.py", line 121, in <module>
    "--shuffle", str(int(args.shuffle)), "--pack-label", "1"])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/usr/local/lib/python2.7/dist-packages/mxnet/tools/im2rec.py', '/home/amcsgpu/Zero/mxnet-ssd-master/data/val.lst', '/home/amcsgpu/Zero/mxnet-ssd-master/data/VOCdevkit', '--shuffle', '1', '--pack-label', '1']' returned non-zero exit status 2
amcsgpu@amcsgpu:~/Zero/mxnet-ssd-master$ ^C

**Comment by zhreshold** [comment]
im2rec.py was updated in mxnet. `--shuffle 1` is not supported, use `--shuffle` instead in prepare_pascal.sh

**Comment by arunbuduri** [comment]
In tools/prepare_pascal.sh, the default value for --shuffle is set to False that is passed as an argument to tools/prepare_dataset.py

In tools/prepare_dataset.py, im2rec.py is called with "--shuffle" option

Since the "--shuffle" option in im2rec.py was renamed as "--no-shuffle", I fixed this issue by changing the file tools/prepare_dataset.py

By changing the line below 
`"--no-shuffle",` str(int(args.shuffle)), "--pack-label", "1"])

to

`"--no-shuffle",` "--pack-label"])

This is a temporary fix since it assumes --no-shuffle always. Ideally, you should read the value passed to tools/prepare_dataset.py and pass "--no-shuffle" or not depending on the value

**Comment by WijdanMTak** [comment]
Hi,
Firstly, thanks very much for your work.
Secondly, I had the same problem and I fixed as you said, but then when I was training it, I got this error:
`
File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 210, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [11:52:31] src/io/input_split_base.cc:173: Check failed: files_.size() != 0U (0 vs. 0) Cannot find any files that matches the URI pattern
`
I have to mention that when I was preparing, it gave me this output: 
`
assert os.path.exists(image_file), 'Path does not exist: {}'.format(image_file)
AssertionError: Path does not exist: /home/eng-wijdan/mxnet-ssd/tools/../data/VOCdevkit/VOC2012/JPEGImages/2009_004217.jpg
`
sorry if I'm borthring you, but I am a bit new, and I just follow the instructions.
looking forward to your reply.
Best regards.

**Comment by zhreshold** [comment]
@WijdanMTak Fix the corrupted files and re-generate the record file should be fine

**Comment by WijdanMTak** [comment]
Thanks for your immediate reply, I really appreciate that.
you are right, since I've posted the question I redownload the corrupted file, and It was solved. :)
but now I'm countering another problem which is :  
`
 File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.8.0: cannot open shared object file: No such file or directory
`
I tried a lot to solve it, one of them was as they refer here but it doesn't work : 
https://github.com/apache/incubator-mxnet/issues/7608
I would be grateful for any suggestion.
Regards.

**Comment by zhreshold** [comment]
@WijdanMTak You can google the problem, it's due to the cuda runtime library not found in PATH.

**Comment by maram992** [comment]
Sir, may I ask a little silly question just to make sure.
Is your implementation could apply on cpu and specifically for non-Nvidia graphics card? 
Many thanks.

**Comment by zhreshold** [comment]
@maram992 just specify use `--cpu`

**Comment by chensonglu** [comment]
@arunbuduri thanks, it works for me
