### ISSUE TITLE
follow the instruction in readme but still encounter error when run python train.py

### ISSUE THREAD

**Issue by kingchenchina** [zhreshold/mxnet-ssd#189]
Error:
RuntimeError: simple_bind error. Arguments:

how to fix it?

error message:
python train.py 
Using mxnet as:
<module 'mxnet' from '/home/cqy/.local/lib/python2.7/site-packages/mxnet/__init__.pyc'>
Warning: using pre-installed version of mxnet may cause unexpected error...
(export MXNET_EXAMPLE_SSD_DISABLE_PRE_INSTALLED=1) to prevent loading pre-installed mxnet.
[10:11:04] src/io/iter_image_det_recordio.cc:281: ImageDetRecordIOParser: /home/cqy/src/mxnet-ssd/data/train.rec, use 23 threads for decoding..
[10:11:04] src/io/iter_image_det_recordio.cc:334: ImageDetRecordIOParser: /home/cqy/src/mxnet-ssd/data/train.rec, label padding width: 350
[10:11:05] src/io/iter_image_det_recordio.cc:281: ImageDetRecordIOParser: /home/cqy/src/mxnet-ssd/data/val.rec, use 23 threads for decoding..
[10:11:05] src/io/iter_image_det_recordio.cc:334: ImageDetRecordIOParser: /home/cqy/src/mxnet-ssd/data/val.rec, label padding width: 350
INFO:root:Start training with (gpu(0)) from pretrained model /home/cqy/src/mxnet-ssd/model/vgg16_reduced
[10:11:06] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[10:11:06] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
INFO:root:Freezed parameters: [conv1_1_weight,conv1_1_bias,conv1_2_weight,conv1_2_bias,conv2_1_weight,conv2_1_bias,conv2_2_weight,conv2_2_bias]
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    tensorboard=args.tensorboard)
  File "/home/cqy/src/mxnet-ssd/train/train_net.py", line 354, in train_net
    monitor=monitor)
  File "/home/cqy/.local/lib/python2.7/site-packages/mxnet/module/base_module.py", line 460, in fit
    for_training=True, force_rebind=force_rebind)
  File "/home/cqy/.local/lib/python2.7/site-packages/mxnet/module/module.py", line 429, in bind
    state_names=self._state_names)
  File "/home/cqy/.local/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 264, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/cqy/.local/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 360, in bind_exec
    shared_group))
  File "/home/cqy/.local/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 638, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/home/cqy/.local/lib/python2.7/site-packages/mxnet/symbol/symbol.py", line 1518, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (32, 3L, 300L, 300L)
label: (32, 58, 6)
[10:11:06] src/storage/storage.cc:118: Compile with USE_CUDA=1 to enable GPU usage

Stack trace returned 10 entries:
[bt] (0) /home/cqy/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x192112) [0x7f3588dca112]
[bt] (1) /home/cqy/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x192738) [0x7f3588dca738]
[bt] (2) /home/cqy/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x27c165a) [0x7f358b3f965a]
[bt] (3) /home/cqy/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x27c6254) [0x7f358b3fe254]
[bt] (4) /home/cqy/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x27c6727) [0x7f358b3fe727]
[bt] (5) /home/cqy/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x22ac571) [0x7f358aee4571]
[bt] (6) /home/cqy/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2335d05) [0x7f358af6dd05]
[bt] (7) /home/cqy/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x233c412) [0x7f358af74412]
[bt] (8) /home/cqy/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x233d7ef) [0x7f358af757ef]
[bt] (9) /home/cqy/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2347d1a) [0x7f358af7fd1a]

**Comment by ddlee-cn** [comment]
```
Compile with USE_CUDA=1 to enable GPU usage
```
means your MXNet is not GPU version.

You may recompile MXNet with USE_CUDA=1 flag, or install it via pypi using "pip install mxnet-cu80".

**Comment by kinraymon** [comment]
If you have gpu , use "pip install mxnet-cu80" to install it
