### ISSUE TITLE
Check failed: allow_null  LocalFileSystem: fail to open "/home/aschu/development/ssd-sample/mxnet-ssd/output/exp1/ssd-symbol.json"

### ISSUE THREAD

**Issue by alexschultz** [zhreshold/mxnet-ssd#190]
python2 train.py --gpu 0 --finetune 1 --end-epoch 20
Using mxnet as:
<module 'mxnet' from '/home/aschu/.virtualenvs/ssd/local/lib/python2.7/site-packages/mxnet/__init__.pyc'>
Warning: using pre-installed version of mxnet may cause unexpected error...
(export MXNET_EXAMPLE_SSD_DISABLE_PRE_INSTALLED=1) to prevent loading pre-installed mxnet.
[22:41:42] src/io/iter_image_det_recordio.cc:281: ImageDetRecordIOParser: /home/aschu/development/ssd-sample/mxnet-ssd/data/train.rec, use 11 threads for decoding..
[22:41:42] src/io/iter_image_det_recordio.cc:334: ImageDetRecordIOParser: /home/aschu/development/ssd-sample/mxnet-ssd/data/train.rec, label padding width: 350
[22:41:42] src/io/iter_image_det_recordio.cc:281: ImageDetRecordIOParser: /home/aschu/development/ssd-sample/mxnet-ssd/data/val.rec, use 11 threads for decoding..
[22:41:43] src/io/iter_image_det_recordio.cc:334: ImageDetRecordIOParser: /home/aschu/development/ssd-sample/mxnet-ssd/data/val.rec, label padding width: 350
INFO:root:Start finetuning with (gpu(0)) from epoch 1
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    tensorboard=args.tensorboard)
  File "/home/aschu/development/ssd-sample/mxnet-ssd/train/train_net.py", line 252, in train_net
    _, args, auxs = mx.model.load_checkpoint(prefix, finetune)
  File "/home/aschu/.virtualenvs/ssd/local/lib/python2.7/site-packages/mxnet/model.py", line 420, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "/home/aschu/.virtualenvs/ssd/local/lib/python2.7/site-packages/mxnet/symbol/symbol.py", line 2518, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/home/aschu/.virtualenvs/ssd/local/lib/python2.7/site-packages/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [22:41:43] src/io/local_filesys.cc:166: Check failed: allow_null  LocalFileSystem: fail to open "/home/aschu/development/ssd-sample/mxnet-ssd/output/exp1/ssd-symbol.json"

Stack trace returned 10 entries:
[bt] (0) /home/aschu/.virtualenvs/ssd/local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2a9e78) [0x7f87b1535e78]
[bt] (1) /home/aschu/.virtualenvs/ssd/local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x293a480) [0x7f87b3bc6480]
[bt] (2) /home/aschu/.virtualenvs/ssd/local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x2930baa) [0x7f87b3bbcbaa]
[bt] (3) /home/aschu/.virtualenvs/ssd/local/lib/python2.7/site-packages/mxnet/libmxnet.so(MXSymbolCreateFromFile+0x4e) [0x7f87b369d13e]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f87f4105e40]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f87f41058ab]
[bt] (6) /home/aschu/.virtualenvs/ssd/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f87f43733df]
[bt] (7) /home/aschu/.virtualenvs/ssd/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f87f4377d82]
[bt] (8) python2(PyEval_EvalFrameEx+0x578f) [0x4c15bf]
[bt] (9) python2(PyEval_EvalCodeEx+0x306) [0x4b9ab6]

**Comment by alexschultz** [comment]
In case anyone else has this issue, I just copied the pre-trained model files (*.json and *.params) to the "output/exp1/" directory, then renamed them to ssd-symbol.json and ssd-001.params and now it appears to be working.
