### ISSUE TITLE
ModuleNotFoundError: No module named 'find_mxnet'

### ISSUE THREAD

**Issue by chaideblog** [zhreshold/mxnet-ssd#200]
<module 'mxnet' from '/home/test/anaconda3/lib/python3.6/site-packages/mxnet/__init__.py'>
Warning: using pre-installed version of mxnet may cause unexpected error...
(export MXNET_EXAMPLE_SSD_DISABLE_PRE_INSTALLED=1) to prevent loading pre-installed mxnet.
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from train.train_net import train_net
  File "/home/test/Projects/mxnet-ssd/train/train_net.py", line 14, in <module>
    from tools.visualize_net import net_visualization
  File "/home/test/Projects/mxnet-ssd/tools/visualize_net.py", line 2, in <module>
    import find_mxnet
ModuleNotFoundError: No module named 'find_mxnet'

**Comment by edmBernard** [comment]
I don't think mxnet-ssd is compatible with python3. 
Your error come from behavior difference in import between python3 and python2.
For a python3 import you need to change this relative import by : `import .find_mxnet`

**Comment by riverhell** [comment]
@chaideblog  i met with the same problem. Try to copy all the codes in 'find_mxnet.py' to 'visualize_net.py', and delete the first two lines.

**Comment by Ctrl-C-V** [comment]
`import sys, os`
`sys.path.append(os.path.join(os.path.dirname(__file__)))`
Do this before `import find_mxnet`
