### ISSUE TITLE
I can't train the model using resnet50 as a network. vgg16_reduced and inception3 works fine.

### ISSUE THREAD

**Issue by renatodmb** [zhreshold/mxnet-ssd#217]
I am trying to train the model using resnet50 but got stucked into the error: 

No google good results and need help.

# python train.py --gpus 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 --batch-size 256 --lr 0.0001 --data-shape 512 --network resnet50 

Using mxnet as:
<module 'mxnet' from '/home/ubuntu/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/mxnet/__init__.pyc'>
Warning: using pre-installed version of mxnet may cause unexpected error...
(export MXNET_EXAMPLE_SSD_DISABLE_PRE_INSTALLED=1) to prevent loading pre-installed mxnet.
[15:16:27] src/io/iter_image_det_recordio.cc:281: ImageDetRecordIOParser: /ML/mxnet-ssd/data/train.rec, use 48 threads for decoding..
[15:16:27] src/io/iter_image_det_recordio.cc:334: ImageDetRecordIOParser: /ML/mxnet-ssd/data/train.rec, label padding width: 350
[15:16:29] src/io/iter_image_det_recordio.cc:281: ImageDetRecordIOParser: /ML/mxnet-ssd/data/val.rec, use 32 threads for decoding..
[15:16:30] src/io/iter_image_det_recordio.cc:334: ImageDetRecordIOParser: /ML/mxnet-ssd/data/val.rec, label padding width: 350
INFO:root:Start training with (gpu(0),gpu(1),gpu(2),gpu(3),gpu(4),gpu(5),gpu(6),gpu(7),gpu(8),gpu(9),gpu(10),gpu(11),gpu(12),gpu(13),gpu(14),gpu(15)) from pretrained model model/ssd_resnet50_512
[15:16:33] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.10.1. Attempting to upgrade...
[15:16:33] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    tensorboard=args.tensorboard)
  File "/ML/mxnet-ssd/train/train_net.py", line 286, in train_net
    output_dir=os.path.dirname(prefix), train=False, num_classes=num_classes)
  File "/ML/mxnet-ssd/tools/visualize_net.py", line 35, in net_visualization
    net = symbol_factory.get_symbol(network, data_shape, num_classes=num_classes)
  File "/ML/mxnet-ssd/tools/../symbol/symbol_factory.py", line 217, in get_symbol
    return symbol_builder.get_symbol(**config)
  File "/ML/mxnet-ssd/symbol/symbol_builder.py", line 157, in get_symbol
    min_filter=min_filter)
  File "/ML/mxnet-ssd/symbol/common.py", line 123, in multi_layer_feature
    layer = internals[from_layer.strip() + '_output']
  File "/home/ubuntu/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/mxnet/symbol/symbol.py", line 514, in __getitem__
    raise ValueError('Cannot find output that matches name \"%s\"' % index)
**ValueError: Cannot find output that matches name "_plus12_output"**

**Comment by zhreshold** [comment]
You should use the pre-trained imagenet models: http://data.dmlc.ml/models/imagenet/resnet/50-layers/ 

not the trained SSD resnet models

**Comment by renatodmb** [comment]
I downloaded and changed, still the same error...

Using mxnet as:
<module 'mxnet' from '/home/ubuntu/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/mxnet/__init__.pyc'>
Warning: using pre-installed version of mxnet may cause unexpected error...
(export MXNET_EXAMPLE_SSD_DISABLE_PRE_INSTALLED=1) to prevent loading pre-installed mxnet.
[12:45:06] src/io/iter_image_det_recordio.cc:281: ImageDetRecordIOParser: /ML/mxnet-ssd/data/train.rec, use 48 threads for decoding..
[12:45:07] src/io/iter_image_det_recordio.cc:334: ImageDetRecordIOParser: /ML/mxnet-ssd/data/train.rec, label padding width: 350
[12:45:10] src/io/iter_image_det_recordio.cc:281: ImageDetRecordIOParser: /ML/mxnet-ssd/data/val.rec, use 32 threads for decoding..
[12:45:11] src/io/iter_image_det_recordio.cc:334: ImageDetRecordIOParser: /ML/mxnet-ssd/data/val.rec, label padding width: 350
INFO:root:Start training with (gpu(0),gpu(1),gpu(2),gpu(3),gpu(4),gpu(5),gpu(6),gpu(7),gpu(8),gpu(9),gpu(10),gpu(11),gpu(12),gpu(13),gpu(14),gpu(15)) from pretrained model model/resnet-50
[12:45:14] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[12:45:14] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    tensorboard=args.tensorboard)
  File "/ML/mxnet-ssd/train/train_net.py", line 286, in train_net
    output_dir=os.path.dirname(prefix), train=False, num_classes=num_classes)
  File "/ML/mxnet-ssd/tools/visualize_net.py", line 35, in net_visualization
    net = symbol_factory.get_symbol(network, data_shape, num_classes=num_classes)
  File "/ML/mxnet-ssd/tools/../symbol/symbol_factory.py", line 217, in get_symbol
    return symbol_builder.get_symbol(**config)
  File "/ML/mxnet-ssd/symbol/symbol_builder.py", line 157, in get_symbol
    min_filter=min_filter)
  File "/ML/mxnet-ssd/symbol/common.py", line 123, in multi_layer_feature
    layer = internals[from_layer.strip() + '_output']
  File "/home/ubuntu/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/mxnet/symbol/symbol.py", line 514, in __getitem__
    raise ValueError('Cannot find output that matches name \"%s\"' % index)
ValueError: Cannot find output that matches name "_plus12_output"

**Comment by zhreshold** [comment]
`--pretrained models/resnet-50 --epoch 0`

**Comment by Jenfree** [comment]
Same error occurred to me. It also shows that 
"raise ValueError('Cannot find output that matches name "%s"' % index)
ValueError: Cannot find output that matches name "_plus12_output"
I tried new params and json from http://data.dmlc.ml/models/imagenet/resnet/50-layers/, and --pretrained models/resnet-50 --epoch 0 also.
But there is still same error. Do you know how to solve this? 
Thanks

**Comment by renatodmb** [comment]
To use the pre-trained model I already add this --pretrained.

So, this is the command I am using:
python train.py --gpus 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15 --batch-size 256 --lr 0.0001 --data-shape 512 --network resnet50 --pretrained model/resnet-50

Same erros.

Using mxnet as:
<module 'mxnet' from '/home/ubuntu/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/mxnet/__init__.pyc'>
Warning: using pre-installed version of mxnet may cause unexpected error...
(export MXNET_EXAMPLE_SSD_DISABLE_PRE_INSTALLED=1) to prevent loading pre-installed mxnet.
[12:36:44] src/io/iter_image_det_recordio.cc:281: ImageDetRecordIOParser: /ML/mxnet-ssd/data/train.rec, use 48 threads for decoding..
[12:36:45] src/io/iter_image_det_recordio.cc:334: ImageDetRecordIOParser: /ML/mxnet-ssd/data/train.rec, label padding width: 350
[12:36:47] src/io/iter_image_det_recordio.cc:281: ImageDetRecordIOParser: /ML/mxnet-ssd/data/val.rec, use 32 threads for decoding..
[12:36:47] src/io/iter_image_det_recordio.cc:334: ImageDetRecordIOParser: /ML/mxnet-ssd/data/val.rec, label padding width: 350
INFO:root:Start training with (gpu(0),gpu(1),gpu(2),gpu(3),gpu(4),gpu(5),gpu(6),gpu(7),gpu(8),gpu(9),gpu(10),gpu(11),gpu(12),gpu(13),gpu(14),gpu(15)) from pretrained model model/resnet-50
[12:36:51] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[12:36:51] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    tensorboard=args.tensorboard)
  File "/ML/mxnet-ssd/train/train_net.py", line 286, in train_net
    output_dir=os.path.dirname(prefix), train=False, num_classes=num_classes)
  File "/ML/mxnet-ssd/tools/visualize_net.py", line 35, in net_visualization
    net = symbol_factory.get_symbol(network, data_shape, num_classes=num_classes)
  File "/ML/mxnet-ssd/tools/../symbol/symbol_factory.py", line 217, in get_symbol
    return symbol_builder.get_symbol(**config)
  File "/ML/mxnet-ssd/symbol/symbol_builder.py", line 157, in get_symbol
    min_filter=min_filter)
  File "/ML/mxnet-ssd/symbol/common.py", line 123, in multi_layer_feature
    layer = internals[from_layer.strip() + '_output']
  File "/home/ubuntu/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/mxnet/symbol/symbol.py", line 514, in __getitem__
    raise ValueError('Cannot find output that matches name \"%s\"' % index)
ValueError: Cannot find output that matches name "_plus12_output"

**Comment by zhreshold** [comment]
It's somehow broken with the visualization code.
You guys can disable https://github.com/zhreshold/mxnet-ssd/blob/master/train/train_net.py#L285 since this is just a visualize helper.


Sorry about the inconvenience.

**Comment by renatodmb** [comment]
Thanks a lot, now it's working!
