### ISSUE TITLE
python demo.py --epoch 0 --images ./data/demo/dog.jpg --thresh 0.5 --cpu --data-shape 300 --network vgg16_reduced

### ISSUE THREAD

**Issue by renatodmb** [zhreshold/mxnet-ssd#218]
[09:30:47] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.9.5. Attempting to upgrade...
[09:30:47] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "demo.py", line 240, in <module>
    sys.exit(main())
  File "demo.py", line 236, in main
    run_images(args, ctx)
  File "demo.py", line 219, in run_images
    ctx, len(class_names), args.nms_thresh, args.force_nms)
  File "demo.py", line 63, in get_detector
    detector = Detector(net, prefix, epoch, data_shape, mean_pixels, ctx=ctx)
  File "/Users/rbbarbos/RnD/Bradesco/incubator-mxnet/example/ssd/detect/detector.py", line 62, in __init__
    self.mod.set_params(args, auxs)
  File "/usr/local/lib/python2.7/site-packages/mxnet/module/module.py", line 350, in set_params
    allow_extra=allow_extra)
  File "/usr/local/lib/python2.7/site-packages/mxnet/module/module.py", line 309, in init_params
    _impl(desc, arr, arg_params)
  File "/usr/local/lib/python2.7/site-packages/mxnet/module/module.py", line 300, in _impl
    raise RuntimeError("%s is not presented" % name)
RuntimeError: fc6_bias is not presented

**Comment by renatodmb** [comment]
Can't run demo using VGG16_reduced

**Comment by renatodmb** [comment]
Any ideias?

**Comment by zhreshold** [comment]
Did you download the  pretrained model?

**Comment by renatodmb** [comment]
Sure!
InceptionV3 and Resnet works!
If I do not download it says file not found.
