### ISSUE TITLE
Cannot start training vgg16_reduced

### ISSUE THREAD

**Issue by ssdevel** [zhreshold/mxnet-ssd#222]
python train.py --num-class 1 --class-name billboard --num-example 936 --train-path records\25_train.rec --val-path records\25_val.rec --gpus 0 --batch-size 16
C:\Users\stefa\Anaconda2\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using mxnet as:
<module 'mxnet' from 'C:\Users\stefa\Anaconda2\lib\site-packages\mxnet\__init__.pyc'>
Warning: using pre-installed version of mxnet may cause unexpected error...
(export MXNET_EXAMPLE_SSD_DISABLE_PRE_INSTALLED=1) to prevent loading pre-installed mxnet.
[21:10:37] c:\jenkins\workspace\mxnet-tag\mxnet\src\io\iter_image_det_recordio.cc:281: ImageDetRecordIOParser: records\25_train.rec, use 7 threads for decoding..
[21:10:38] c:\jenkins\workspace\mxnet-tag\mxnet\src\io\iter_image_det_recordio.cc:334: ImageDetRecordIOParser: records\25_train.rec, label padding width: 350
[21:10:46] c:\jenkins\workspace\mxnet-tag\mxnet\src\io\iter_image_det_recordio.cc:281: ImageDetRecordIOParser: records\25_val.rec, use 7 threads for decoding..
[21:10:46] c:\jenkins\workspace\mxnet-tag\mxnet\src\io\iter_image_det_recordio.cc:334: ImageDetRecordIOParser: records\25_val.rec, label padding width: 350
INFO:root:Start training with (gpu(0)) from pretrained model C:\Users\stefa\Desktop\mxnet-ssd-master\model\vgg16_reduced
[21:10:49] c:\jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:209: Loading symbol saved by previous version v0.9.5. Attempting to upgrade...
[21:10:49] c:\jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:217: Symbol successfully upgraded!
INFO:root:Freezed parameters: [conv1_1_weight,conv1_1_bias,conv1_2_weight,conv1_2_bias,conv2_1_weight,conv2_1_bias,conv2_2_weight,conv2_2_bias]
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    tensorboard=args.tensorboard)
  File "C:\Users\stefa\Desktop\mxnet-ssd-master\train\train_net.py", line 355, in train_net
    monitor=monitor)
  File "C:\Users\stefa\Anaconda2\lib\site-packages\mxnet\module\base_module.py", line 488, in fit
    allow_missing=allow_missing, force_init=force_init)
  File "C:\Users\stefa\Anaconda2\lib\site-packages\mxnet\module\module.py", line 309, in init_params
    _impl(desc, arr, arg_params)
  File "C:\Users\stefa\Anaconda2\lib\site-packages\mxnet\module\module.py", line 297, in _impl
    cache_arr.copyto(arr)
  File "C:\Users\stefa\Anaconda2\lib\site-packages\mxnet\ndarray\ndarray.py", line 1970, in copyto
    return _internal._copyto(self, out=other)
  File "<string>", line 25, in _copyto
  File "C:\Users\stefa\Anaconda2\lib\site-packages\mxnet\_ctypes\ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "C:\Users\stefa\Anaconda2\lib\site-packages\mxnet\base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:10:53] c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\elemwise_op_common.h:123: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node  at 0-th output: expected [84], got [8]

**Comment by Belinda-great** [comment]
i think the num_filters is not right, you can check it.
