### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by wisdomk** [zhreshold/mxnet-ssd#230]
when I am running the demo.py file am receiving the following error
```
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import tools.find_mxnet
  File "C:\Users\wisdom\Desktop\mxnet-ssd-master\tools\find_mxnet.py", line 6, in <module>
    import mxnet as mx
  File "C:\Users\wisdom\Anaconda3\envs\gpu-test\lib\site-packages\mxnet\__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "C:\Users\wisdom\Anaconda3\envs\gpu-test\lib\site-packages\mxnet\context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "C:\Users\wisdom\Anaconda3\envs\gpu-test\lib\site-packages\mxnet\base.py", line 213, in <module>
    _LIB = _load_lib()
  File "C:\Users\wisdom\Anaconda3\envs\gpu-test\lib\site-packages\mxnet\base.py", line 204, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "C:\Users\wisdom\Anaconda3\envs\gpu-test\lib\ctypes\__init__.py", line 353, in __init__
    self._handle = _dlopen(self._name, mode)
```
I tried to see where the error is triggered, as shown it ...\lib\ctypes\__init__.py line 353 where 
`self._handle = _dlopen(self._name, mode)`

so I debugged it and printed the content of 'self._name' which shows

> >>>> kernel32
> >>>> C:\Users\wisdom\Anaconda3\envs\gpu-test\lib\site-packages\mxnet\libmxnet.dll

at the moment of firing the error. I checked the existence of the requested .dll file and it is certainly exists but why it fires the error I didn't understand!

**Comment by wisdomk** [comment]
weirdly enough...I tried to run python prompt and just import ctypes as following
```
from _ctypes import LoadLibrary as _dlopen
_dlopen("what\\ever\\path\\libmxnet.dll")
```
and it stills throws the same error just like it doesn't see the file at all, or maybe there is some dependency missing!
on the other hand, whatever other .dll file I try to load it goes perfectly well!

**Comment by wisdomk** [comment]
Ok finally solved!

I got to know that such error could be thrown when the file dependencies are not satisfied or not found. So to check the dependencies you go first to Visual Studio Prompt and then navigate to the folder where `libmxnet.dll` exists and run the following command

`dumpbin /dependents libmxnet.dll`

and it will show you a list of required files.

What was missing in my case are some of `nVidia GPU Computing Toolkit` files `Cuda 9.0` as `libmxnet.dll` asks for them and I was having toolkit version 10.0 instead!
