### ISSUE TITLE
fail to prepare dataset using python

### ISSUE THREAD

**Issue by JerrySor** [zhreshold/mxnet-ssd#240]
python tools/prepare_dataset.py --dataset pascal --year 2012 --set trainval --target ./data/train.lst
dyld: warning, LC_RPATH ${ORIGIN} in /Users/sorpiseth/Library/Python/2.7/lib/python/site-packages/mxnet/libmxnet.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH ${ORIGIN} in /Users/sorpiseth/Library/Python/2.7/lib/python/site-packages/mxnet/libmxnet.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/sorpiseth/Library/Python/2.7/lib/python/site-packages/cv2/.dylibs/QtWidgets being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/sorpiseth/Library/Python/2.7/lib/python/site-packages/cv2/.dylibs/QtGui being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/sorpiseth/Library/Python/2.7/lib/python/site-packages/cv2/.dylibs/QtCore being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/sorpiseth/Library/Python/2.7/lib/python/site-packages/cv2/.dylibs/QtTest being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/sorpiseth/Library/Python/2.7/lib/python/site-packages/cv2/.dylibs/QtConcurrent being ignored in restricted program because of @executable_path
filtering images with no gt-labels. can abort filtering using *true_negative* flag
... remaining 11540/11540 images.  
saving list to disk...
List file ./data/train.lst generated...
dyld: warning, LC_RPATH ${ORIGIN} in /Users/sorpiseth/Library/Python/2.7/lib/python/site-packages/mxnet/libmxnet.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH ${ORIGIN} in /Users/sorpiseth/Library/Python/2.7/lib/python/site-packages/mxnet/libmxnet.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/sorpiseth/Library/Python/2.7/lib/python/site-packages/cv2/.dylibs/QtWidgets being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/sorpiseth/Library/Python/2.7/lib/python/site-packages/cv2/.dylibs/QtGui being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/sorpiseth/Library/Python/2.7/lib/python/site-packages/cv2/.dylibs/QtCore being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/sorpiseth/Library/Python/2.7/lib/python/site-packages/cv2/.dylibs/QtTest being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Users/sorpiseth/Library/Python/2.7/lib/python/site-packages/cv2/.dylibs/QtConcurrent being ignored in restricted program because of @executable_path
usage: im2rec.py [-h] [--list] [--exts EXTS [EXTS ...]] [--chunks CHUNKS]
                 [--train-ratio TRAIN_RATIO] [--test-ratio TEST_RATIO]
                 [--recursive] [--no-shuffle] [--pass-through]
                 [--resize RESIZE] [--center-crop] [--quality QUALITY]
                 [--num-thread NUM_THREAD] [--color {-1,0,1}]
                 [--encoding {.jpg,.png}] [--pack-label]
                 prefix root
im2rec.py: error: unrecognized arguments: --shuffle 1 1
Traceback (most recent call last):
  File "tools/prepare_dataset.py", line 121, in <module>
    "--shuffle", str(int(args.shuffle)), "--pack-label", "1"])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/Users/sorpiseth/Library/Python/2.7/lib/python/site-packages/mxnet/tools/im2rec.py', '/Users/sorpiseth/Desktop/mxnet-ssd-master/data/train.lst', '/Users/sorpiseth/Desktop/mxnet-ssd-master/data/VOCdevkit', '--shuffle', '1', '--pack-label', '1']' returned non-zero exit status 2

====

Could you advice me please?

**Comment by JerrySor** [comment]
I solve that problem already.
