### ISSUE TITLE
Saving checkpoint failed !!

### ISSUE THREAD

**Issue by Tyler-D** [zhreshold/mxnet-ssd#30]
I used the framework to train the VGG16_reduced network on my own dataset. It trained well but I found it failed to save checkpoint. And the error traceback is as follows:
```
INFO:root:Saved checkpoint to "/home/caffemaker/MXNet/mxnet/example/ssd/model/ssd_500-0001.params"
[10:26:02] /home/caffemaker/MXNet/mxnet/dmlc-core/include/dmlc/logging.h:235: [10:26:02] src/ndarray/ndarray.cc:231: Check failed: from.shape() == to->shape() operands shape mismatch
Traceback (most recent call last):
  File "train_zface.py", line 78, in <module>
    args.lr_refactor_ratio, args.monitor, args.log_file)
  File "/home/caffemaker/MXNet/mxnet/example/ssd/train/train_net.py", line 201, in train_net_on_others
    monitor=monitor)
  File "/home/caffemaker/MXNet/mxnet/python/mxnet/module/base_module.py", line 408, in fit
    batch_end_callback=eval_batch_end_callback, epoch=epoch)
  File "/home/caffemaker/MXNet/mxnet/python/mxnet/module/base_module.py", line 169, in score
    self.forward(eval_batch, is_train=False)
  File "/home/caffemaker/MXNet/mxnet/python/mxnet/module/module.py", line 388, in forward
    self._exec_group.forward(data_batch, is_train)
  File "/home/caffemaker/MXNet/mxnet/python/mxnet/module/executor_group.py", line 319, in forward
    _load_label(data_batch, self.label_arrays, self.label_layouts)
  File "/home/caffemaker/MXNet/mxnet/python/mxnet/module/executor_group.py", line 49, in _load_label
    _load_general(batch.label, targets, major_axis)
  File "/home/caffemaker/MXNet/mxnet/python/mxnet/module/executor_group.py", line 36, in _load_general
    d_dst_copy.copyto(d_dst)
  File "/home/caffemaker/MXNet/mxnet/python/mxnet/ndarray.py", line 533, in copyto
    return _internal._copyto(self, out=other)
  File "/home/caffemaker/MXNet/mxnet/python/mxnet/ndarray.py", line 1225, in unary_ndarray_function
    c_array(ctypes.c_char_p, [c_str(str(i)) for i in kwargs.values()])))
  File "/home/caffemaker/MXNet/mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:26:02] src/ndarray/ndarray.cc:231: Check failed: from.shape() == to->shape() operands shape mismatch
```
I changed the SSD_VGG16_Reduced architecture a little, including the from layers and the class numbers.
And I tried the framework in this repository and the dmlc repository ---- Same error.
Did I make some mistakes or is it a bug ? @zhreshold Thanks for help !

**Comment by zhreshold** [comment]
Saving checkpoint is done. The error occurs when validation is started. The label shape in validation set mismatch with the data. So I guess there's something wrong with your code.

Post your modified train_net.py please.

**Comment by Tyler-D** [comment]
Here is the modified train_net.py and some dataset stuff. I simply followed the example. @zhreshold 
```python
def load_others(name, list_file, image_dir, label_dir, shuffle=True):
    #TODO:
    classes = ["background", "face"]
    imdbs = []
    imdbs.append(TxtFormat(name, classes, list_file, image_dir, label_dir))
    return imdbs[0]
def convert_pretrained(name, args):
    """
    Special operations need to be made due to name inconsistance, etc

    Parameters:
    ---------
    args : dict
        loaded arguments

    Returns:
    ---------
    processed arguments as dict
    """
    if name == 'vgg16_reduced':
        args['conv6_bias'] = args.pop('fc6_bias')
        args['conv6_weight'] = args.pop('fc6_weight')
        args['conv7_bias'] = args.pop('fc7_bias')
        args['conv7_weight'] = args.pop('fc7_weight')
        del args['fc8_weight']
        del args['fc8_bias']
    return args

def train_net_on_others(net, train_set, train_list, image_dir, label_dir, batch_size,
               data_shape, mean_pixels, resume, finetune, pretrained, epoch, prefix,
               ctx, begin_epoch, end_epoch, frequent, learning_rate, momentum,
               weight_decay, val_set, val_list, lr_refactor_epoch, lr_refactor_ratio,
               iter_monitor=0, log_file=None):
    # set up logger
    logging.basicConfig()
    logger = logging.getLogger()
    logger.setLevel(logging.INFO)
    if log_file:
        fh = logging.FileHandler(log_file)
        logger.addHandler(fh)

    # check args
    if isinstance(data_shape, int):
        data_shape = (data_shape, data_shape)
    assert len(data_shape) == 2, "data_shape must be (h, w) tuple or list or int"
    prefix += '_' + str(data_shape[0])

    if isinstance(mean_pixels, (int, float)):
        mean_pixels = [mean_pixels, mean_pixels, mean_pixels]
    assert len(mean_pixels) == 3, "must provide all RGB mean values"

    # load dataset
    imdb = load_others(train_set, train_list, image_dir, label_dir)
    val_imdb = load_others(val_set, val_list, image_dir, label_dir)

    # init data iterator
    train_iter = DetIter(imdb, batch_size, data_shape, mean_pixels,
                         cfg.TRAIN.RAND_SAMPLERS, cfg.TRAIN.RAND_MIRROR,
                         cfg.TRAIN.EPOCH_SHUFFLE, cfg.TRAIN.RAND_SEED,
                         is_train=True)
    # save per N epoch, avoid saving too frequently
    resize_epoch = int(cfg.TRAIN.RESIZE_EPOCH)
    if resize_epoch > 1:
        batches_per_epoch = ((imdb.num_images - 1) / batch_size + 1) * resize_epoch
        train_iter = mx.io.ResizeIter(train_iter, batches_per_epoch)
    train_iter = mx.io.PrefetchingIter(train_iter)
    if val_imdb:
        val_iter = DetIter(val_imdb, batch_size, data_shape, mean_pixels,
                           cfg.VALID.RAND_SAMPLERS, cfg.VALID.RAND_MIRROR,
                           cfg.VALID.EPOCH_SHUFFLE, cfg.VALID.RAND_SEED,
                           is_train=True)
        val_iter = mx.io.PrefetchingIter(val_iter)
    else:
        val_iter = None

    # load symbol
    sys.path.append(os.path.join(cfg.ROOT_DIR, 'symbol'))
    net = importlib.import_module("symbol_" + net).get_symbol_train(imdb.num_classes)

    # define layers with fixed weight/bias
    fixed_param_names = [name for name in net.list_arguments() \
        if name.startswith('conv1_') or name.startswith('conv2_')]

    # load pretrained or resume from previous state
    ctx_str = '('+ ','.join([str(c) for c in ctx]) + ')'
    if resume > 0:
        logger.info("Resume training with {} from epoch {}"
            .format(ctx_str, resume))
        _, args, auxs = mx.model.load_checkpoint(prefix, resume)
        begin_epoch = resume
    elif finetune > 0:
        logger.info("Start finetuning with {} from epoch {}"
            .format(ctx_str, finetune))
        _, args, auxs = mx.model.load_checkpoint(prefix, finetune)
        begin_epoch = finetune
        # the prediction convolution layers name starts with relu, so it's fine
        fixed_param_names = [name for name in net.list_arguments() \
            if name.startswith('conv')]
    elif pretrained:
        logger.info("Start training with {} from pretrained model {}"
            .format(ctx_str, pretrained))
        _, args, auxs = mx.model.load_checkpoint(pretrained, epoch)
        args = convert_pretrained(pretrained, args)
    else:
        logger.info("Experimental: start training from scratch with {}"
            .format(ctx_str))
        args = None
        auxs = None
        fixed_param_names = None

    # helper information
    if fixed_param_names:
        logger.info("Freezed parameters: [" + ','.join(fixed_param_names) + ']')

    # init training module
    mod = mx.mod.Module(net, label_names=('label',), logger=logger, context=ctx,
                        fixed_param_names=fixed_param_names)

    # fit
    batch_end_callback = mx.callback.Speedometer(train_iter.batch_size, frequent=frequent)
    epoch_end_callback = mx.callback.do_checkpoint(prefix)
    iter_refactor = lr_refactor_epoch * imdb.num_images / train_iter.batch_size
    lr_scheduler = mx.lr_scheduler.FactorScheduler(iter_refactor, lr_refactor_ratio)
    optimizer_params={'learning_rate':learning_rate,
                      'momentum':momentum,
                      'wd':weight_decay,
                      'lr_scheduler':lr_scheduler,
                      'clip_gradient':None,
                      'rescale_grad': 1.0}
    monitor = mx.mon.Monitor(iter_monitor, pattern=".*") if iter_monitor > 0 else None

    initializer = mx.init.Mixed([".*scale", ".*"], \
        [ScaleInitializer(), mx.init.Xavier(magnitude=1)])

    mod.fit(train_iter,
            eval_data=val_iter,
            eval_metric=MultiBoxMetric(),
            batch_end_callback=batch_end_callback,
            epoch_end_callback=epoch_end_callback,
            optimizer='sgd',
            optimizer_params=optimizer_params,
            begin_epoch=begin_epoch,
            num_epoch=end_epoch,
            initializer=initializer,
            arg_params=args,
            aux_params=auxs,
            allow_missing=True,
            monitor=monitor)


class TxtFormat(Imdb):
    def __init__(self, name, classes, list_file, image_dir, label_dir, \
                 extension='', label_extension='', shuffle=True):
        if isinstance(classes, list) or isinstance(classes, tuple):
            num_classes = len(classes)
        elif isinstance(classes, str):
            with open(classes, 'r') as f:
                classes = [l.strip() for l in f.readlines()]
                num_classes = len(classes)
        else:
            raise ValueError, "classes should be list/tuple or text file"
        assert num_classes > 0, "number of classes must > 0"
# call superior class init()
        super(TxtFormat, self).__init__(name + '_' + str(num_classes))
        self.classes = classes
        self.num_classes = num_classes
        self.list_file = list_file
        self.image_dir = image_dir
        self.label_dir = label_dir
        self.extension = extension
        self.label_extension = label_extension

        self.image_set_index, self.label_set_index = self._load_image_set_index_and_label_set_index(shuffle)
        self.num_images = len(self.image_set_index)
        self.labels = self._load_image_labels()


    def _load_image_set_index_and_label_set_index(self, shuffle):
        assert os.path.exists(self.list_file), 'Path does not exists: {}'.format(self.list_file)
        with open(self.list_file, 'r') as f:
        # construct the file list
            image_anno_pair_list = [x for x in f.readlines()]
            if shuffle:
                np.random.shuffle(image_anno_pair_list)
            image_set_index = []
            label_set_index = []
            for pair in image_anno_pair_list:
                image_set_index.append(pair.split()[0])
                label_set_index.append(pair.split()[-1])
        return image_set_index, label_set_index

    def image_path_from_index(self, index):
        assert self.image_set_index is not None, "Dataset not initialized"
        name = self.image_set_index[index]
        image_file = os.path.join(self.image_dir, name) + self.extension
        assert os.path.exists(image_file), 'Path does not exist: {}'.format(image_file)
        return image_file

    def label_from_index(self, index):
        assert self.labels is not None, "Labels not processed"
        return self.labels[index, :, :]

    def _label_path_from_index(self, index):
        label_file = os.path.join(self.label_dir, index + self.label_extension)
        assert os.path.exists(label_file), 'Path does not exist: {}'.format(label_file)
        return label_file

    def _load_image_labels(self):
        temp = []
        max_objects = 0

        # load ground-truths
        for idx in xrange(len(self.image_set_index)):
            label_file = self.label_set_index[idx]
            img_path = self.image_set_index[idx]
            img = Image.open(img_path)
            width = img.size[0]
            height = img.size[1]
            # print "Processing {}".format(label_file)
            with open(label_file, 'r') as f:
                label = []
                for line in f.readlines():
                    temp_label = line.split()
                    assert len(temp_label) == 5, "Invalid label file" + label_file
                    cls_id = int(temp_label[0])
                    xmin = float(temp_label[1]) / width
                    ymin = float(temp_label[2]) / height
                    xmax = float(temp_label[3]) / width
                    ymax = float(temp_label[4]) / height
                    # print "TXT FORMAT LABEL: {}".format([cls_id, xmin, ymin, xmax, ymax])
                    label.append([cls_id, xmin, ymin, xmax, ymax])
                temp.append(np.array(label))
                max_objects = max(max_objects, len(label))
        # add padding to labels so that the dimensions match in each batch
        assert max_objects > 0, "No objects found for any of the images"
        self.padding = max_objects
        labels = []
        for label in temp:
            label = np.lib.pad(label, ((0, max_objects-label.shape[0]), (0,0)), \
                               'constant', constant_values=(-1, -1))
            labels.append(label)
        return np.array(labels)
```

**Comment by zhreshold** [comment]
On this line
```
self.padding = max_objects
# debug the max_objects value in both train and val dataset
print max_objects
```
I guess the padded label size mismatch in train_iter and val_iter, the problem is, train/val dataset don't know each other when label is loaded.
To fix it, give a larger initial value of max_objects(larger than the maximum objects in any image).

**Comment by Tyler-D** [comment]
@zhreshold  Exactly Right! A larger initial value of max_objects makes it work! 
```
INFO:root:Epoch[0] Train-Acc=0.822090
INFO:root:Epoch[0] Train-ObjectAcc=0.518519
INFO:root:Epoch[0] Train-SmoothL1=5.582390
INFO:root:Epoch[0] Time cost=3104.384
INFO:root:Saved checkpoint to "/home/caffemaker/MXNet/mxnet/example/ssd/model/ssd_500-0001.params"
INFO:root:Epoch[0] Validation-Acc=0.851005
INFO:root:Epoch[0] Validation-ObjectAcc=0.493257
INFO:root:Epoch[0] Validation-SmoothL1=7.393969
INFO:root:Epoch[1] Batch [20]	Speed: 2.58 samples/sec	Train-Acc=0.841674
```
But I think there should be a more elegant way to solve it instead of  setting a empirical value directly here. 
Anyway, it works! Thanks.

**Comment by zhreshold** [comment]
You are right, but the only way to make this work is seems to be synchronizing the padding number after they are both created. I will modify the behavior later.
