### ISSUE TITLE
I got a TypeError when I run the demo.py,is this because of python3?

### ISSUE THREAD

**Issue by AndyVer2** [zhreshold/mxnet-ssd#32]
Traceback (most recent call last):
  File "demo.py", line 98, in <module>
    CLASSES, args.thresh, args.show_timer)
  File "E:\SSD\mxnet-ssd\detect\detector.py", line 163, in detect_and_visualize
    dets = self.im_detect(im_list, root_dir, extension, show_timer=show_timer)
  File "E:\SSD\mxnet-ssd\detect\detector.py", line 94, in im_detect
    return self.detect(test_iter, show_timer)
  File "E:\SSD\mxnet-ssd\detect\detector.py", line 60, in detect
    detections = self.mod.predict(det_iter).asnumpy()
  File "C:\Users\winan\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\module\base_module.py", line 246, in predict
    for nbatch, eval_batch in enumerate(eval_data):
  File "C:\Users\winan\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\io.py", line 66, in __next__
    return self.next()
  File "C:\Users\winan\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\io.py", line 275, in next
    if self.iter_next():
  File "C:\Users\winan\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\io.py", line 264, in iter_next
    self.current_batch = DataBatch(sum([batch.data for batch in self.next_batch], []),
***TypeError: can only concatenate list (not "dict_values") to list***

**Comment by zhreshold** [comment]
Either windows or py3 could be the cause. I haven't tested either.

**Comment by AndyVer2** [comment]
Thanks,I changed py3 to py2,there is no error.
