### ISSUE TITLE
cannot find the files when i run demo.py

### ISSUE THREAD

**Issue by rencheng123456** [zhreshold/mxnet-ssd#36]
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import tools.find_mxnet
  File "/media/ubuntu/266AA4086AA3D33B/ccCorkSpace/deeplearnings/ssd/src/mxnet-ssd/tools/find_mxnet.py", line 7, in <module>
    import mxnet as mx
  File "/media/ubuntu/266AA4086AA3D33B/ccCorkSpace/deeplearnings/ssd/src/mxnet-ssd/tools/../mxnet/python/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/media/ubuntu/266AA4086AA3D33B/ccCorkSpace/deeplearnings/ssd/src/mxnet-ssd/tools/../mxnet/python/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/media/ubuntu/266AA4086AA3D33B/ccCorkSpace/deeplearnings/ssd/src/mxnet-ssd/tools/../mxnet/python/mxnet/base.py", line 34, in _load_lib
    lib_path = libinfo.find_lib_path()
  File "/media/ubuntu/266AA4086AA3D33B/ccCorkSpace/deeplearnings/ssd/src/mxnet-ssd/tools/../mxnet/python/mxnet/libinfo.py", line 36, in find_lib_path
    'List of candidates:\n' + str('\n'.join(dll_path)))
RuntimeError: Cannot find the files.
List of candidates:
/media/ubuntu/266AA4086AA3D33B/ccCorkSpace/deeplearnings/ssd/src/mxnet-ssd/mxnet/python/mxnet/libmxnet.so
/media/ubuntu/266AA4086AA3D33B/ccCorkSpace/deeplearnings/ssd/src/mxnet-ssd/mxnet/python/mxnet/../../lib/libmxnet.so
/media/ubuntu/266AA4086AA3D33B/ccCorkSpace/deeplearnings/ssd/src/mxnet-ssd/mxnet/python/mxnet/../../build/Release/libmxnet.so
/usr/local/lib/libmxnet.so
/opt/ros/kinetic/lib/libmxnet.so
/usr/local/lib/libmxnet.so
/usr/local/cuda-8.0/lib64/libmxnet.so

What should i do to solve this problem

**Comment by zhreshold** [comment]
import mxnet not found, compilation succeed?
