### ISSUE TITLE
Slower than Caffe at test time

### ISSUE THREAD

**Issue by cory8249** [zhreshold/mxnet-ssd#42]
Hi,

I use both this version and original caffe version, and test same image (data/demo/dog.jpg) with GTX1070 GPU, CUDA 8.0, CUDNN 5.1

Caffe:    14 ms (71 fps)
MXNet:  33 ms (33 fps)

MXNet is 2x slower, is it normal ?
Thanks in advance

**Comment by zhreshold** [comment]
Don't measure with single image. The time spend in loading the library is different.

**Comment by cory8249** [comment]
I want to build a real-time video object detection system, so input are fed one by one continuously. I originally used "caffe time" script command to benchmark, but I found that it is much faster than what I really measured in python. Here is my new fair test:
Caffe: 28 ms
MXNet: 33 ms

Thanks

**Comment by zhreshold** [comment]
Are you using detector.detect to process images one by one? I admit there's more we could optimize, such as the way we load and resize the inputs.

**Comment by cory8249** [comment]
I simply use im_detect() in a for loop. I found that it will create testDB (seemed not necessary for my app), so I am going to modify it myself.

**Comment by niufuren** [comment]
I have the same problem with cory8249. Could you specify the methods that optimize the performance? When measuring the performance, the runtime of loading and resizing image are not considered.

**Comment by niufuren** [comment]
@cory8249 I found if you just test the runtime of `self.mod.predict(det_iter)` not `self.mod.predict(det_iter).asnumpy()` in the function detect, the speed result will be much improved. For more solutions, you can go to https://github.com/zhreshold/mxnet-ssd/issues/4

**Comment by 315386775** [comment]
@niufuren when i modify as you said. Can you give me some solutions.  I get the error:

Detection time for 1 images: 0.0639 sec
Traceback (most recent call last):
  File "demo_cell.py", line 133, in <module>
    class_names, args.thresh, args.show_timer)
  File "/home/mxnet/example/ssd/detect/detector.py", line 167, in detect_and_visualize
    dets = self.im_detect(im_list, root_dir, extension, show_timer=show_timer)
  File "/home/mxnet/example/ssd/detect/detector.py", line 98, in im_detect
    return self.detect(test_iter, show_timer)
  File "/home/mxnet/example/ssd/detect/detector.py", line 72, in detect
    res = det[np.where(det[:, 0] >= 0)[0]]
  File "/home/anaconda2/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/ndarray.py", line 504, in __getitem__
    str(key), str(type(key))))
  File "/home/anaconda2/lib/python2.7/site-packages/numpy/core/numeric.py", line 1869, in array_str
    return array2string(a, max_line_width, precision, suppress_small, ' ', "", str)
  File "/home/anaconda2/lib/python2.7/site-packages/numpy/core/arrayprint.py", line 442, in array2string
    elif reduce(product, a.shape) == 0:
  File "/home/anaconda2/lib/python2.7/site-packages/mxnet-0.10.1-py2.7.egg/mxnet/ndarray.py", line 274, in __bool__
    raise ValueError("The truth value of an NDArray is ambiguous. " \
ValueError: The truth value of an NDArray is ambiguous. Please convert to number with asscalar() first.

**Comment by edmBernard** [comment]
@niufuren @315386775 ndarray api make some computation asynchronously. https://github.com/apache/incubator-mxnet/issues/6974
so if you want to time ndarray computation, you need to be sure computation are finished. You can either call asnumpy() or wait_to_read()
