### ISSUE TITLE
I got this when I ran the demo.py

### ISSUE THREAD

**Issue by shootingliu** [zhreshold/mxnet-ssd#46]
C:\Users\LST\mxnet-ssd-master>python demo.py
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    from detect.detector import Detector
  File "C:\Users\LST\mxnet-ssd-master\detect\detector.py", line 63
    print "Detection time for {} images: {:.4f} sec".format(
                                                   ^
SyntaxError: invalid syntax

with win10, anaconda3.THX~~

**Comment by zhreshold** [comment]
python 3 don't support print syntax, you need to modify the code a bit or use python2.7 instead

**Comment by shootingliu** [comment]
I changed 2 into 3 for tensorflow just a couple of days ago. I will try 2, thanks a lot.

**Comment by shootingliu** [comment]
@zhreshold AttributeError: 'module' object has no attribute 'Scale',with python2.......is it my own mistake?

**Comment by shootingliu** [comment]
need to install scale?and how.THX~

**Comment by MyAusweis** [comment]
in python 2 print "test", in python 3 use print ("test")
