### ISSUE TITLE
Error when run "python demo.py"

### ISSUE THREAD

**Issue by FlyingZXC** [zhreshold/mxnet-ssd#5]
environment: windows 10, mxnet compiled from source

error message:
Traceback (most recent call last):                                                                                                                                                                        
  File "demo.py", line 95, in <module>                                                                                                                                                                    
    ctx, args.nms_thresh, args.force_nms)                                                                                                                                                                 
  File "demo.py", line 39, in get_detector                                                                                                                                                                
    .get_symbol(len(CLASSES), nms_thresh, force_nms)                                                                                                                                                      
  File "D:\learning_mxnet\mxnet-ssd\symbol\symbol_vgg16_reduced.py", line 162, in get_symbol                                                                                                              
    net = get_symbol_train(num_classes)                                                                                                                                                                   
  File "D:\learning_mxnet\mxnet-ssd\symbol\symbol_vgg16_reduced.py", line 118, in get_symbol_train                                                                                                        
    clip=True, interm_layer=0)                                                                                                                                                                            
  File "D:\learning_mxnet\mxnet-ssd\symbol\common.py", line 111, in multibox_layer                                                                                                                        
    from_layer = mx.symbol.Scale(data=from_layer, mode="spatial", \                                                                                                                                       
AttributeError: module 'mxnet.symbol' has no attribute 'Scale'       

And I didn't found a symbol "Scale" in the mxnet document. Is it a customized layer definition?

**Comment by zhreshold** [comment]
There are several custom layers. So you have to build the mxnet with them.

**Comment by FlyingZXC** [comment]
Yes, I found some new files in "mxnet" directory. I am a newbie to python. Is it possible that you can briefly explain how to design custom layers? Thx!

**Comment by zhreshold** [comment]
Check this out: http://mxnet.io/how_to/new_op.html
You have multiple options to create new layers.
I prefer creating C++/CUDA layers rather than in python.

**Comment by FlyingZXC** [comment]
Thanks!
