### ISSUE TITLE
Error on execution with custom trained model : Operands shape mismatch

### ISSUE THREAD

**Issue by edmBernard** [zhreshold/mxnet-ssd#7]
I train a new model with this command : 
```
python2 train.py --prefix ssd20161027 --devkit-path data/mydata/ --gpus 0 --val-image-set val --image-set train --year 2016 --batch-size 16
```
and when I test on datas (mines or demos) with : 
```
python demo.py --epoch 4 --images data/mydata/JPEGImages/102355_119.jpg --thresh 0.5 --prefix ssd20161027
```

The script failed with this error : 
```
[11:48:32] /path/to/my/project/mxnet-ssd/mxnet/dmlc-core/include/dmlc/logging.h:235: [11:48:32] src/ndarray/ndarray.cc:291: Check failed: from.shape() == to->shape() operands shape mismatch
Traceback (most recent call last):
  File "demo.py", line 95, in <module>
    ctx, args.nms_thresh, args.force_nms)
  File "demo.py", line 41, in get_detector
    data_shape, mean_pixels, ctx=ctx)
  File "/path/to/my/project/mxnet-ssd/detect/detector.py", line 37, in __init__
    self.mod.set_params(args, auxs)
  File "/path/to/my/project/mxnet-ssd/tools/../mxnet/python/mxnet/module/base_module.py", line 478, in set_params
    allow_missing=allow_missing, force_init=force_init)
  File "/path/to/my/project/mxnet-ssd/tools/../mxnet/python/mxnet/module/module.py", line 190, in init_params
    _impl(name, arr, arg_params)
  File "/path/to/my/project/mxnet-ssd/tools/../mxnet/python/mxnet/module/module.py", line 180, in _impl
    cache_arr.copyto(arr)
  File "/path/to/my/project/mxnet-ssd/tools/../mxnet/python/mxnet/ndarray.py", line 499, in copyto
    return _internal._copyto(self, out=other)
  File "/path/to/my/project/mxnet-ssd/tools/../mxnet/python/mxnet/ndarray.py", line 1174, in unary_ndarray_function
    c_array(ctypes.c_char_p, [c_str(str(i)) for i in kwargs.values()])))
  File "/path/to/my/project/mxnet-ssd/tools/../mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [11:48:32] src/ndarray/ndarray.cc:291: Check failed: from.shape() == to->shape() operands shape mismatch
```

I'm on ubuntu 16.04 with cuda 8.0 and cudnn5

**Comment by edmBernard** [comment]
I got my mistake, I forgot to change the number of classes in the demo script. 😞 
btw thanks for your work on this model.
