### ISSUE TITLE
Got below error when try demo.py

### ISSUE THREAD

**Issue by siyiding1216** [zhreshold/mxnet-ssd#70]
Traceback (most recent call last):
  File "demo.py", line 108, in <module>
    ctx, args.nms_thresh, args.force_nms)
  File "demo.py", line 46, in get_detector
    .get_symbol(len(CLASSES), nms_thresh, force_nms)
  File "/home/local/ANT/siyiding/mxnet-ssd/symbol/symbol_vgg16_ssd_300.py", line 179, in get_symbol
    net = get_symbol_train(num_classes)
  File "/home/local/ANT/siyiding/mxnet-ssd/symbol/symbol_vgg16_ssd_300.py", line 127, in get_symbol_train
    num_channels=num_channels, clip=False, interm_layer=0, steps=steps)
  File "/home/local/ANT/siyiding/mxnet-ssd/symbol/common.py", line 176, in multibox_layer
    clip=clip, name="{}_anchors".format(from_name), steps=step)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/_ctypes/symbol.py", line 181, in creator
    ctypes.byref(sym_handle)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/base.py", line 78, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Cannot find argument 'steps', Possible Arguments:
----------------
sizes : , optional, default=(1,)
    List of sizes of generated MultiBoxPriores.
ratios : , optional, default=(1,)
    List of aspect ratios of generated MultiBoxPriores.
clip : boolean, optional, default=False
    Whether to clip out-of-boundary boxes.
, in operator _contrib_MultiBoxPrior(name="", clip="False", sizes="(0.1,0.141)", ratios="(1,2,0.5)", steps="(0.02666666666666667, 0.02666666666666667)")

**Comment by zhreshold** [comment]
Please update mxnet in submodule, not the one in official repo
