### ISSUE TITLE
Have AttributeError when try demo.py

### ISSUE THREAD

**Issue by chenweiqian** [zhreshold/mxnet-ssd#73]
Traceback (most recent call last):
  File "demo.py", line 99, in <module>
    ctx, args.nms_thresh, args.force_nms)
  File "demo.py", line 40, in get_detector
    .get_symbol(len(CLASSES), nms_thresh, force_nms)
  File "/home/wahaha/mxnet-ssd/symbol/symbol_vgg16_ssd_300.py", line 179, in get_symbol
    net = get_symbol_train(num_classes)
  File "/home/wahaha/mxnet-ssd/symbol/symbol_vgg16_ssd_300.py", line 100, in get_symbol_train
    stride=(1,1), act_type="relu", use_batchnorm=False)
  File "/home/wahaha/mxnet-ssd/symbol/common.py", line 35, in conv_act_layer
    init=mx.init.Constant(0.0), attr={'__lr_mult__': '2.0'})
AttributeError: module 'mxnet.initializer' has no attribute 'Constant'

@zhreshold  I didn't find any solution . Hope you can help me! Thanks!!

**Comment by zhreshold** [comment]
Make sure you have updated the submodule mxnet

**Comment by chenweiqian** [comment]
@zhreshold  Thank you！
