### ISSUE TITLE
Error when we predict on image and not from DataIter

### ISSUE THREAD

**Issue by edmBernard** [zhreshold/mxnet-ssd#9]
when i try to call the model on one image with the example here : https://github.com/dmlc/mxnet/blob/master/tests/python/predict/mxnet_predict_example.py

my code : 
```
    predictor = mx.model.FeedForward.load("model/ssd20161028_300", 10, ctx=mx.gpu(0), numpy_batch_size=1)
    img = cv2.imread('data/Total/JPEGImages/video_20160728_142541_299.jpg')
    img_arr = np.asarray(img)
    img_arr = np.swapaxes(img_arr, 0, 2)
    img_arr = np.swapaxes(img_arr, 1, 2)
    img2 = img_arr.reshape((1, 3, 960, 540))
    print predictor.predict(img2)[0]
```

I got this error on execution :
```
[17:34:32] /my/project/mxnet-ssd/mxnet/dmlc-core/include/dmlc/logging.h:235: [17:34:32] src/operator/./multibox_target-inl.h:274: Check failed: (lshape.ndim()) == (3) Label should be [batch-num_labels-5] tensor
Traceback (most recent call last):
  File "demo.py", line 95, in <module>
    print predictor.predict(img2)[0]
  File "/my/project/mxnet-ssd/tools/../mxnet/python/mxnet/model.py", line 597, in predict
    self._init_predictor(data_shapes)
  File "/my/project/mxnet-ssd/tools/../mxnet/python/mxnet/model.py", line 528, in _init_predictor
    self.ctx[0], grad_req='null', **dict(input_shapes))
  File "/my/project/mxnet-ssd/tools/../mxnet/python/mxnet/symbol.py", line 671, in simple_bind
    arg_shapes, _, aux_shapes = self.infer_shape(**kwargs)
  File "/my/project/mxnet-ssd/tools/../mxnet/python/mxnet/symbol.py", line 453, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File "/my/project/mxnet-ssd/tools/../mxnet/python/mxnet/symbol.py", line 513, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/my/project/mxnet-ssd/tools/../mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: InferShape Error in multibox_target: [17:34:32] src/operator/./multibox_target-inl.h:274: Check failed: (lshape.ndim()) == (3) Label should be [batch-num_labels-5] tensor
```

Have you any idea how to pass image to your model without DataIter ?

**Comment by zhreshold** [comment]
Convert to deploy net first, you are using network with loss functions.
Check this out: deploy.py

**Comment by edmBernard** [comment]
thx it work perfectly
