### ISSUE TITLE
Unable to load inception and resnet checkpoints

### ISSUE THREAD

**Issue by mmmikael** [zhreshold/mxnet-ssd#98]
I am getting this error when trying to load the checkpoints of the 2 new models `Inception-v3 512x512` and `Resnet-50 512x512`:

```bash
$ python demo.py 
[13:58:43] src/nnvm/legacy_json_util.cc:185: Warning: loading symbol saved by MXNet version 1001 with lower version of MXNet v1000. May cause undefined behavior. Please update MXNet if you encounter any issue
[13:58:43] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:304: [13:58:43] src/ndarray/ndarray.cc:695: Check failed: fi->Read(data) Invalid NDArray file format

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x18b0dc) [0x7f5b414c00dc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xc6980e) [0x7f5b41f9e80e]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(MXNDArrayLoad+0x265) [0x7f5b41e662b5]
[bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f5b504f2e40]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f5b504f28ab]
[bt] (5) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f5b507603df]
[bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f5b50764d82]
[bt] (7) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (8) python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (9) python(PyEval_EvalCodeEx+0x255) [0x4c2765]

Traceback (most recent call last):
  File "demo.py", line 121, in <module>
    ctx, len(class_names), args.nms_thresh, args.force_nms)
  File "demo.py", line 38, in get_detector
    detector = Detector(net, prefix, epoch, data_shape, mean_pixels, ctx=ctx)
  File "/home/mikael/dev/mxnet/example/ssd/detect/detector.py", line 34, in __init__
    load_symbol, args, auxs = mx.model.load_checkpoint(model_prefix, epoch)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/model.py", line 374, in load_checkpoint
    save_dict = nd.load('%s-%04d.params' % (prefix, epoch))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/ndarray.py", line 2100, in load
    ctypes.byref(names)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 84, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [13:58:43] src/ndarray/ndarray.cc:695: Check failed: fi->Read(data) Invalid NDArray file format

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x18b0dc) [0x7f5b414c00dc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xc6980e) [0x7f5b41f9e80e]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(MXNDArrayLoad+0x265) [0x7f5b41e662b5]
[bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f5b504f2e40]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f5b504f28ab]
[bt] (5) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f5b507603df]
[bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f5b50764d82]
[bt] (7) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (8) python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (9) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
```

My config:
* Ubuntu 16.04.2 LTS 
* Python 2.7.12
* mxnet 0.10.0*

**Comment by mmmikael** [comment]
I compiled from sources and it fixes this issue. 

It looks like checkpoints saved with mxnet 0.10.1 cannot load be loaded with earlier versions.
